// <auto-generated />
using RiasBot.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace RiasBot.Migrations
{
    [DbContext(typeof(KurumiContext))]
    [Migration("20180222004744_Kurumi")]
    partial class Kurumi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("RiasBot.Services.Database.Models.GuildConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Bye");

                    b.Property<ulong>("ByeChannel");

                    b.Property<string>("ByeMessage");

                    b.Property<DateTime?>("DateAdded");

                    b.Property<bool>("Greet");

                    b.Property<ulong>("GreetChannel");

                    b.Property<string>("GreetMessage");

                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("MuteRole");

                    b.Property<string>("Prefix");

                    b.Property<bool>("XpGuildNotification");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("RiasBot.Services.Database.Models.Patreon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateAdded");

                    b.Property<DateTime>("NextTimeReward");

                    b.Property<int>("Reward");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patreon");
                });

            modelBuilder.Entity("RiasBot.Services.Database.Models.UserConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Currency");

                    b.Property<DateTime?>("DateAdded");

                    b.Property<int>("Level");

                    b.Property<DateTime>("MessageDateTime");

                    b.Property<ulong>("UserId");

                    b.Property<int>("Xp");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RiasBot.Services.Database.Models.Waifus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateAdded");

                    b.Property<bool>("IsPrimary");

                    b.Property<ulong>("UserId");

                    b.Property<int>("WaifuId");

                    b.Property<string>("WaifuName");

                    b.Property<string>("WaifuPicture");

                    b.Property<int>("WaifuPrice");

                    b.Property<string>("WaifuUrl");

                    b.HasKey("Id");

                    b.ToTable("Waifus");
                });

            modelBuilder.Entity("RiasBot.Services.Database.Models.Warnings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateAdded");

                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("Moderator");

                    b.Property<string>("Reason");

                    b.Property<ulong>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Warnings");
                });

            modelBuilder.Entity("RiasBot.Services.Database.Models.XpSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateAdded");

                    b.Property<ulong>("GuildId");

                    b.Property<int>("Level");

                    b.Property<DateTime>("MessageDateTime");

                    b.Property<ulong>("UserId");

                    b.Property<int>("Xp");

                    b.HasKey("Id");

                    b.ToTable("XpSystem");
                });
#pragma warning restore 612, 618
        }
    }
}
